services:
  - type: web
    name: blueme-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node simple-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
